openapi: 3.1.0
info:
  title: Dog API
  version: 1.0.0
paths: { }
components:
  schemas:
    RandomDogImage:
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
        status:
          type: string
      required: [ message, status ]