components:
  schemas:
    RandomDogImage:
      type: object
      additionalProperties: false
      properties:
        message:
          type: string
        status:
          type: string
      required: [ message, status ]