# Reusable workflow to publish consumer pact contracts to the broker.
name: 'Pact - Publish Contract'

on:
  workflow_call:
    inputs:
      pact_broker_base_url:
        required: true
        type: string
      consumer_version:
        description: 'The version of the consumer.'
        required: true
        type: string
      branch_name:
        description: 'Name of the branch that originates the consumer version.'
        required: true
        type: string
      artifact_name:
        description: 'The name of the artifact containing the pacts to publish.'
        required: true
        type: string
    secrets:
      pact_broker_token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Pact CLI'
        uses: ./.github/actions/pact-cli-setup

      - name: 'Download pacts artifact'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./pacts-to-publish

      - name: 'Publish pacts to broker'
        env:
          PACT_BROKER_BASE_URL: ${{ inputs.pact_broker_base_url }}
          PACT_BROKER_TOKEN: ${{ secrets.pact_broker_token }}
        run: |
          pact-broker publish ./pacts-to-publish \
            --consumer-app-version=${{ inputs.consumer_version }} \
            --branch=${{ inputs.branch_name }}