# Reusable workflow to simulate a deployment for didactic purposes.
name: 'Reusable - Deploy'

on:
  workflow_call:
    inputs:
      pacticipant:
        description: 'The name of the component being deployed.'
        required: true
        type: string
      version:
        description: 'The version of the component.'
        required: true
        type: string
      environment:
        description: 'The target environment for the deployment.'
        required: true
        type: string

jobs:
  fake-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 'Simulate deployment action'
        run: |
          echo "✅ [Simulated] Deploying ${{ inputs.pacticipant }} version ${{ inputs.version }} to ${{ inputs.environment }}..."
          echo "Deployment step completed successfully."