# Reusable workflow to check if a component version can be deployed to an environment.
name: 'Reusable - Can I deploy'

on:
  workflow_call:
    inputs:
      pact_broker_base_url:
        required: true
        type: string
      pacticipant:
        description: 'The name of the component being deployed.'
        required: true
        type: string
      version:
        description: 'The version of the component.'
        required: true
        type: string
      environment:
        description: 'The target environment for the deployment.'
        required: true
        type: string
    secrets:
      pact_broker_token:
        required: true

jobs:
  can-i-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Pact CLI'
        uses: ./.github/actions/pact-cli-setup

      - name: 'Pact Broker Can I Deploy'
        env:
          PACT_BROKER_BASE_URL: ${{ inputs.pact_broker_base_url }}
          PACT_BROKER_TOKEN: ${{ secrets.pact_broker_token }}
        run: |
          pact-broker can-i-deploy \
            --pacticipant ${{ inputs.pacticipant }} \
            --version ${{ inputs.version }} \
            --to-environment ${{ inputs.environment }} \
            --retry-while-unknown=5 \
            --retry-interval=15