name: '[Student Provider] - Build, Verify & Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to. Select 'NONE' for build only."
        required: true
        type: choice
        default: 'NONE'
        options: [ NONE, DEV, PRE, PROD ]

env:
  PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACTICIPANT: "student-provider"
  MAVEN_CLI_OPTS: >
    --batch-mode --errors --fail-at-end --show-version
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build_and_verify:
    name: Build & Verify Pacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17', cache: 'maven' }

      - name: Build and Verify with Maven
        run: >
          mvn -f student-provider/pom.xml $MAVEN_CLI_OPTS clean install
          -Dpact.verifier.publishResults=true
          -Dpact.provider.version=${{ github.sha }}
          -Dpact.provider.branch=${{ github.ref_name }}
          -Dpactbroker.consumerversionselectors.rawjson='[{"deployedOrReleased":true}, {"matchingBranch": true}]'

  can_i_deploy:
    name: Can I Deploy?
    if: github.event.inputs.environment != 'NONE'
    needs: build_and_verify
    uses: ./.github/workflows/reusables/can-i-deploy.yml
    with:
      pact_broker_base_url: ${{ env.PACT_BROKER_BASE_URL }}
      pacticipant: ${{ env.PACTICIPANT }}
      version: ${{ github.sha }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      pact_broker_token: ${{ secrets.PACTFLOW_TOKEN }}

  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    if: github.event.inputs.environment != 'NONE'
    needs: check_deployment_gate
    uses: ./.github/workflows/reusables/deploy.yml
    with:
      pacticipant: ${{ env.PACTICIPANT }}
      version: ${{ github.sha }}
      environment: ${{ github.event.inputs.environment }}

  tag_deployment:
    name: Tag Deployment in Pact Broker
    if: github.event.inputs.environment != 'NONE'
    needs: perform_deployment
    uses: ./.github/workflows/reusables/tagging.yml
    with:
      pact_broker_base_url: ${{ env.PACT_BROKER_BASE_URL }}
      pacticipant: ${{ env.PACTICIPANT }}
      version: ${{ github.sha }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      pact_broker_token: ${{ secrets.PACTFLOW_TOKEN }}